### ISSUE TITLE
pv.io is undefined

### ISSUE THREAD

**Issue by stared** [biasmv/pv#100]
I try to follow the docs - [Getting started with PV](https://pv.readthedocs.org/en/latest/intro.html).

However, `pv.io` turns out to be `undefined`, so the line with `pv.io.fetchPdb` causes the problem.

Are you sure that `pv.io` is present in the minified version?

**Comment by biasmv** [comment]
Thanks for the report. I tried to reproduce the problem with the minified version but without success. Could you give some more details on what you did?

Best,
Marco

**Comment by stared** [comment]
Thanks for developing this library. :)

http://jsfiddle.net/stared/096qLst2/ -> look at the console

It uses `pv.min.js` file from http://biasmv.github.io/pv/js/pv.min.js (BTW: it may be useful to provide a way to directly download a standalone minified js from the repo).

**Comment by biasmv** [comment]
Oh, I see. I haven't updated the demo for a long time. The ```pv.io``` namespace has only been added in recent versions. Before the ```io``` namespace only existed as a separate top-level namespace. ```pv.io``` was introduced to have everything in one namespace for AMD. If you use the minified file without AMD, you will still be able to use the ```io``` namespace for backwards compatibility. The docs just don't mention it anymore :).

I've just updated the demo to use the latest version of PV. You can grab the new minified file from there. There are also zip files for the latest releases available here: https://github.com/biasmv/pv/releases. I haven't gotten around to providing the 1.6.0 zip file.

Best,
Marco

**Comment by stared** [comment]
Thanks! It turned out to be my own fault/omission.

It any case, it would be really convenient to provide in "getting started" the easiest approach (i.e. directly downloading minified version, instead of making one's own build, which takes time). Plus, there is some inconsistency in using names `pv.min.js` and `bio-pv.min.js`.

**Comment by biasmv** [comment]
Yes, you are right. The getting started guide should be updated. Will try to get to it soon.

Best,
Marco
