### ISSUE TITLE
Feature request: click events on Mesh objects

### ISSUE THREAD

**Issue by mriffle** [biasmv/pv#101]
Greetings, I am very impressed by pv and am successfully using it for some pretty cool bioinformatics projects. One feature I do wish it had was handling click events on tubes and spheres added via addTube()  Do you think this would be possible? Thanks.

**Comment by biasmv** [comment]
Glad you like it.

I have just pushed support for click events in a separate branch. It should do what you need. Some more work is required to update the docs and make sure that we are completely backward compatible:

Check out the custom-mesh-click-events branch (https://github.com/biasmv/pv/tree/custom-mesh-click-events) . You can use it like this:


```js
  viewer.clear();
  var go = viewer.customMesh('custom');
  go.addSphere([-10, 0, 0], 2, { userData : 'one' } );
  go.addSphere([10, 0, 0], 2, { userData : 'two' } );
  go.addSphere([0, -10, 0], 2, { userData : 'three' } );
  go.addSphere([0, 10, 0], 2, { userData : 'four' } );
  go.addSphere([0, 0, -10], 2, { userData : 'five' } );
  go.addSphere([0, 0, 10], 2, { userData : 'six' } );
  viewer.setCenter([0,0,0], 2, { userData : 'seven' } );
  viewer.setZoom(20);
  viewer.on('doubleClicked', function(picked) {
    if (picked === null) return;
    viewer.setCenter(picked.pos());
    console.log('click target', picked.target(), ', node: ', picked.node());
  });
```

**Comment by biasmv** [comment]
I've merged the branch back into master and updated the documentation. Let me know if this does what you want.

**Comment by mriffle** [comment]
Fantastic, I'll try this out as soon as possible. Thank you!

On Sat, Jun 13, 2015 at 3:46 AM, Marco Biasini <notifications@github.com>
wrote:

> I've merged the branch back into master and updated the documentation. Let
> me know if this does what you want.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biasmv/pv/issues/101#issuecomment-111697761>.
>



-- 
Michael Riffle
Informatics and Data Manager
Yeast Resource Center & UW Proteomics Resource
University of Washington, Seattle

**Comment by mriffle** [comment]
Hi, thank you so much for implementing this. I have been working with the new version and it does precisely what I had hoped for and it looks to be working well.

**Comment by biasmv** [comment]
Great, good to know!
