### ISSUE TITLE
Support to highlight custom region

### ISSUE THREAD

**Issue by fabsta** [biasmv/pv#103]
Hi!
First of all, great tool! I really enjoy using it.

Is there a way to highlight parts of a structure that were hit by 
a database search? E.g. you have a query, search it against PDB
and then highlight on the structure, where it matched a particular entry.

Would be great to have feature like this (or maybe it already exists, but
I couldn't find it in the documentation)

Thanks!

**Comment by stared** [comment]
You can use [coloring](https://pv.readthedocs.org/en/latest/coloring.html), e.g. to set colors differently for different atoms. You can do it after a structure is drawn.

    function highlightFrom(start) {
      return new pv.color.ColorOp(function(atom, out, index) {
        if (atom.index() > start) {
          out[index+0] = 1.0; // R
          out[index+1] = 0.0; // G
          out[index+2] = 0.0; // B
          out[index+3] = 1.0; // A
        } else {
          out[index+0] = 0.0;
          out[index+1] = 1.0;
          out[index+2] = 0.0;
          out[index+3] = 0.5;
        }
      });
    }

**Comment by biasmv** [comment]
@stared's solution is currently the way to go. As outline in my comment on issue #104, I've got a special highlight mode in one of my local branches. If there is interest, I can try to get this into master and make this a standard feature.

**Comment by andreasprlic** [comment]
Having a dedicated highlight mode would be great. It could be used to map sequence features onto PV.

**Comment by biasmv** [comment]
@fabsta, @stared: For the sake of completeness: You actually don't need to write your own color operation to change color for a sub structure. You can pass in a view as the second argument to colorBy. In that case, colorBy only applies the color to parts of the structure contained in the view.

```js
var go = viewer.cartoon('cartoon', structure);
var selected = structure.select({rnumRange : [15,20]});
go.colorBy(color.uniform('red'), selected);
```

**Comment by stared** [comment]
@biasmv I didn't know it. Thanks!

**Comment by biasmv** [comment]
I've added a small sample that shows how to highlight the atom under the cursor here:

http://pv.readthedocs.org/en/latest/samples/hover.html

**Comment by biasmv** [comment]
Find attached a screenshot of a first custom region highlighting implementation which has been pushed to master a few minutes ago.

 It currently only works for mesh-based geometries (cartoon, tube, trace, ballsAndSticks, spheres). I decided against the glow implementation as it was too slow in Chrome/Firefox. Framerates dropped below the acceptable level. 

It looks best with a dark background, but I don't see why it shouldn't also work with with a white background when using a different highlighting color.

![highlight](https://cloud.githubusercontent.com/assets/1254268/8441165/e568396a-1f76-11e5-9c7b-2c8634a69ef0.png)

**Comment by ppillot** [comment]
Brilliant !
that’s exactly the feature we were looking for before integrating pv in our project.
It renders selections exactly as Chimera does.
By the way, there is a very convenient way in Chimera to make and see selections based upon mouse click and keyboard interactions : to start a selection, one press the Ctrl key and clicks on a residue. Then, still pressing the Ctrl key, pressing the up-arrow key extends the selection to the whole chain, and pressing it again extends the selection to the whole molecule.
Do you think that such mouse and key binding events could be feasible in pv (just a question, not a feature request !)
Paul

**Comment by mizuchi3** [comment]
Great stuff Marco, this is really useful !

Keep up the good work!

**Comment by stared** [comment]
@biasmv Wow, thanks! +!

**Comment by biasmv** [comment]
@ppillot:

Yes, that's certainly feasible and in fact implementing this was the next item on my todo list :). Having that said, if you want to help out on that area, that would be appreciated.

There are different aspects to what you request:
- handling the mouse clicks itself to get the object (atom, residue) under the cursor. That's already possible using ``viewer.on('click', ...)``, or ``viewer.on('doubleClick', ...)``. In additition you can manually request to get the object at a certain x,y coordinate using viewer.pick(). This can easily be done outside the viewer.
- updating the selection as a result of user-interaction. Essentially this boils down to adding/removing atoms from the selection view and calling renderedMolecule.setSelection(view). This can also be done outside the viewer itself by only using MolView and friends. It's possible there are a few features missing from the MolView, ResidueView and AtomView classes in particular concerning removing parts from views again. But these are easy to add.

- rendering the selections. That's partially implemented now. I'll still have to implement it for the line-based geometries and add a few knobs to tweak the looks (selection color etc). Also, there is currently no documentation for the feature.


On a tangent, I don't think it's a good idea to pre-define too much keyboard mouse interaction as part of the viewer itself. Instead these things should be done as part of a plugin. Only users that actually need the functionality will have to include in on their site. It's also easier to switch to a different type of keyboard/mouse interaction if one wishes to do so. I'm thinking of something along the lines of

```js
var viewer = pv.Viewer(...); 
var thePlugin = pluginInNeedOfAGoodName({ ... });
// configure the plug in, e.g. by adding additional event handlers 
// for selection change events etc, or configure the actual keys.
thePlugin.on('selection', function() { ... });

// add the plugin to the viewer. This will call thePlugin.initialise(viewer) 
// once the viewer is ready. thePlugin.initialise would then register all 
// callbacks on the viewer() and make the appropriate changes to the rendering.
viewer.addPlugin(thePlugin);
```

In case you are wondering, the plugin system also doesn't exist yet. The plugin system is optional, but I think it would help to abstract away the "how" from the user.

The 'selection interaction' plugin could be officially bundled with PV, and given the number of requests for such functionality that would even make sense as it still takes a substantial amount of code implement the selection handling by hand.

I should be able to finish the PV-internal part of it (selection rendering, selection docs, plugin system, additions to MolView) at some point next week. If you are interested to help with the actual selection handling "a la chimera" that would be great.

Best,
Marco

**Comment by fabsta** [comment]
Thanks a lot! This is really really cool!

**Comment by biasmv** [comment]
With the latest commits, I'd call the selection highlighting code production-ready. You can check out a sample of the highlighting code here: http://pv.readthedocs.org/en/latest/sample-select.html

This will be part of the 1.8 release.

**Comment by mizuchi3** [comment]
That’s great!

I have to report that the return key does not center on my Firefox 39. Its working in IE and Chrome. 

But that could be more to do with readthedocs ? I see the page is trying to load 3 items, but failing. 



-----Original Message-----

**Comment by biasmv** [comment]
Should work now in FF as well.

**Comment by mizuchi3** [comment]
works on my home laptop, I will confirm if it works on my browser at work on Monday

________________________________

**Comment by mizuchi3** [comment]
Yes, works on my Firefox at work !
