### ISSUE TITLE
Clicks on atoms do not work

### ISSUE THREAD

**Issue by stared** [biasmv/pv#105]
I tried to add callbacks for clicks on atoms (as in https://pv.readthedocs.org/en/latest/viewer.html#viewer-events), but I've failed.

In a viewer I had a rendered `pdb` and I wanted to show position of a clicked atom. But neither of `viewer.on('click', func)` or `viewer.addListener('click', func)` does work for me (it does not even console log - it seems to be never fired). (BTW: What is the difference between `.on` and `.addListener`?)

Is there any gotcha to make it working? (Or is it some kind of bug?)

In any case, a minimal example with clicking would be really useful. (Vide #71)

**Comment by biasmv** [comment]
'click', 'doubleClick' have been a very recent addition to the API. For older versions, you will have to use this:

https://pv.readthedocs.org/en/v1.5.0/viewer.html#mouse-interaction-events-atomclicked-atomdoubleclicked

**Comment by biasmv** [comment]
Now, for the longer answer:

click/doubleClick were added just a few commits ago. Before click and doubleClick handlers had to be registered through atomClick/atomDoubleClicked (which still works by the way). The main reason for renaming them was to make it clear that click events are also returned when clicking non-molecular objects, e.g. geometry added through customMesh(), or when clicking the background. Along the way, I've also significantly simplified the code that needs to be written for click handlers. Handlers written for the old interface should continue to work, I've tried to be 100% backwards compatible. Well with the exception of cases where code isn't expecting to receive click events for custom mesh objects.


Regarding your second question: viewer.on/viewer.addListener are aliases, they behave exactly the same. 

Your request for more samples is duly noted.

**Comment by stared** [comment]
Thanks, `atomClicked` works! (But I will go with the newest version possible; in any case, comments in docs like "new in 1.6" would be super helpful.)

It took me some time to guess to to access index:

    viewer.on('atomClicked', function(picked) {
      console.log("clicked on: ", picked);
      if (picked === null) return;
      console.log("index", picked.object().atom.index());
    });

**Comment by biasmv** [comment]
Yes, I agree. I'll  add an introduced-in tag for new features to void such confusion in the future.
