### ISSUE TITLE
What about Bower ?

### ISSUE THREAD

**Issue by grrseguin** [biasmv/pv#108]
Hello,

I'm interrested to use *Protein viewer* in my project. For to integrate it, do you think to use a JS library like [Bower](http://bower.io/docs/creating-packages/) ?

Thanks,

**Comment by biasmv** [comment]
I personally don't use bower, but I can see that it's useful. I've just pushed small changeset that adds a bower.json file to the release packages. You should now be able to bower install the release tgz's:

    bower install https://github.com/biasmv/pv/releases/download/v1.7.1/bio-pv-1.7.1.tgz

You can't however install directly from the git repository. For now at least.

**Comment by Traksewt** [comment]
Is there any plan to register bio-pv with bower ? That would be nice and neat. Especially once we start doing other packages that depend on pv (pv plugins that require pv).

**Comment by biasmv** [comment]
You can now download and install PV with ``bower install bio-pv``
