### ISSUE TITLE
focus on transparent element

### ISSUE THREAD

**Issue by Traksewt** [biasmv/pv#111]
Text controls, such as up and down arrows, are tricky to implement on PV, as the key listener must listen to the document, and those keys may have other effects (like page scrolling).

One alternative is to set the focus on a hidden (transparent) item and the PV key listeners can listen to that element. That way PV has a concept of focus. Whenever there is a mouse click, PV will programatically regain focus. 

Here is one way:
http://stackoverflow.com/questions/10851402/setting-focus-on-hidden-textbox-field-using-javascript
with pointer-events:none; to disable clicking.

Adding key listeners can be added to PV directly, making this implementation detail hidden to the user.

**Comment by biasmv** [comment]
I've implemented a variant of the approach suggested in the stackoverflow post. Just let me know if it works for you.

**Comment by biasmv** [comment]
Just discovered a nasty side-effect of using a hidden text element to simulate focus: On tablets/phones, the on-screen keyboard shows up when tapping the viewer for the first time. I'll have to see if there is a way to work around this.
