### ISSUE TITLE
LineGeom is not defined

### ISSUE THREAD

**Issue by mizuchi3** [biasmv/pv#114]
Hello Marco,
Using the latest master branch, I find my original call to create lines for ligands fails, is there a new way to use this method? 

pv_viewer.lines('template.ligands_lines',pv_structure.select({'chain':'_'}));

ReferenceError: LineGeom is not defined
var lineGeom = new LineGeom(gl, opts.float32Allocator);
bio-pv....8610261 (line 5101, col 8)

Its line 5101 of my debug code, which I guess might not be the same as yours, its in 
  exports.lines = function (structure, gl, opts) {
    console.time('lines');
    var vertAssoc = new AtomVertexAssoc(structure, true);
    opts.color.begin(structure);
    var lineGeom = new LineGeom(gl, opts.float32Allocator);

**Comment by mizuchi3** [comment]
I have no problem with tag v1.8.1, so is that the solution, I should stick with the latest release?

**Comment by biasmv** [comment]
Thank's for the report. I've fixed the issue in master. It was a bug in AMDclean that caused the problem. 

I wouldn't use master for anything in production right now. The new billboard spheres shader is still work in progress and will require a few more tweaks before it's a full replacement. 

Best,
Marco
