### ISSUE TITLE
Translate camera with middle mouse button

### ISSUE THREAD

**Issue by harryjubb** [biasmv/pv#115]
Hello,

First may I say, this project is incredible! What you've achieved is very impressive and a pleasure to use.

I wanted to ask if it would be possible to add translation of the camera when holding down the middle mouse button. This would make the experience much more familiar to PyMOL users.

All the best,

Harry

**Comment by biasmv** [comment]
Thanks for the kind words. I'm glad you like it.

I've added support for middle-mouse panning in one of the last commits. Can you test if this does what you want?

Best,
Marco

**Comment by harryjubb** [comment]
Apologies for the delay in my response.

I've got the middle mouse panning working in the demo running the `serve` command, but not when emulating the "setting up a small website" from the documentation. The viewer works but middle mouse panning doesn't; am I missing something? I tried including:

    <script type='text/javascript' src='./pv/src/mouse.js'></script>

But this didn't help. I tried using both bower and by cloning the git repository.

Thanks again for your help :).

**Comment by biasmv** [comment]
Hey,

sorry for the late reply. I've had a few very busy days and didn't have time to look into your problem until now. Can you try again? I haven't updated the bio-pv.min.js when I committed the changes, that's why you were most likely using a version that didn't yet have the mouse adjustments. The version which is committed works for me in a small demo.

**Comment by harryjubb** [comment]
Hey,

No problem, same here! Am preparing for a presentation in which I intend to use (and advertise :D) PV.

I updated to the latest release and it's working now, thank you so much! Am looking forward to continuing to use PV :)
