### ISSUE TITLE
Getter methods for camera position

### ISSUE THREAD

**Issue by harryjubb** [biasmv/pv#118]
Hi (again!),

I'm not sure if I'm missing something but I'm struggling to find a way to get the current rotation, center and zoom of the camera for the viewer (e.g. to save specific views). Is this currently possible? I looked at trying to access the viewer's _cam property directly but couldn't get this to work (my javascript hackery is limited!)

Best wishes,

Harry

**Comment by biasmv** [comment]
Don't ask me why, but most of them have been missing. I've just added viewer.rotation(), viewer.center() (viewer.zoom() already existed). The following will print the rotation (as mat4), center of rotation and the zoom factor

```js
console.log('rotation:', pv.mat4.str(viewer.rotation()), 
            ', center:', pv.vec3.str(viewer.center()), 
            ', zoom:', viewer.zoom());

```

**Comment by harryjubb** [comment]
Ah ok, thank you! I saw the zoom one but it threw an error when I was using the minified release. I actually got to them in the end by finding the obfuscated _cam using the Chrome javascript inspector! (it's _d inside the viewer in the version I'm using) But using the getters is much better of course :D
