### ISSUE TITLE
byAtomProp, item.prop is not a function

### ISSUE THREAD

**Issue by mizuchi3** [biasmv/pv#119]
Hi Marco,

Im trying to colour by tempFactor, (eventually with a gradient as well), but at the moment Im failing to even colour using the simple atom index as a test. 

var tube = pv_viewer.tube(serverName, pv_structure.select('protein') );
1: tube.colorBy(pv.color.uniform('cyan'))
2: tube.colorBy(pv.color.byChain());
3: tube.colorBy( pv.color.byAtomProp('index') )
4: tube.colorBy( pv.color.byAtomProp('tempFactor') )

1 and 2 work, 3 and 4 fail with the following error in function getMinMaxRange(obj, iter, propName):
TypeError: item.prop is not a function
var value = item.prop(propName);

**Comment by mizuchi3** [comment]
I can get it to work if I use      

 var value = item[propName]();

Is this the solution?

**Comment by mizuchi3** [comment]
That comment didnt work, how 

'var value = item[propName]();'

**Comment by mizuchi3** [comment]
Wow, use backticks, to leave code in comments!

**Comment by mizuchi3** [comment]
I also have to change one more line, to get the gradients to work:

`function colorByItemProp(propName, grad, range, iter, item) {
 ................
      t = (item(a)[propName]() - this._min) / (this._max - this._min);
 ...............................`

**Comment by biasmv** [comment]
Thanks for the report. I've fixed the issue in the latest commit by adding the missing implementation of prop for AtomView.

Best,
Marco
