### ISSUE TITLE
Rainbow color direction

### ISSUE THREAD

**Issue by mizuchi3** [biasmv/pv#120]
Hi Marco,

I just noticed that PV rainbow colours are the opposite order to jmol and molscript, I wondered if you noticed, or is there a reason for the reversal of colour from N to C terminal?

**Comment by mizuchi3** [comment]
The same is true for AstexViewer, ie blue at the N-terminus to red at the C-terminus

**Comment by biasmv** [comment]
I've reversed the rainbow direction in the latest version.
