### ISSUE TITLE
mouse event sync between viewers

### ISSUE THREAD

**Issue by px172** [biasmv/pv#121]
Dear developers, 

Thanks for your effort of implementing the great viewer. Is it possible to sync mouse actions between two viewers ? For example, when user rotate/zoom the structure in viewer1, structure in viewer2 will also be rotated/zoomed.

**Comment by biasmv** [comment]
It's not possible right now, but it would be relatively easy to add. What's your intended use-case? Do you want to synchronize two viewers for side-by-side stereo? If so, I'd recommend another approach as providing frame synchronization between two viewers is going to be tricky.

**Comment by px172** [comment]
I am using viewers to show ligand binding site predictions for a given protein structure. For example, viewer1 shows the result of protein-protein binding site prediction for protein X. viewer2 shows the result of epitope prediction for the same protein. (Predictions are colored on protein surface). If the mouse is synchronized, the view points of two viewers will be identical. User can compare the results easily.

**Comment by biasmv** [comment]
I've pushed a change that allows you to sync the orientation between two viewers. Here is a sample of how you can do it: 

http://pv.readthedocs.org/en/latest/viewer.html#camera-position-rotation-zoom-changed-event-experimental

This is not part of any release yet, you will have to get the latest minified version from here: 

https://raw.githubusercontent.com/biasmv/pv/master/bio-pv.min.js

Let me know if this works for you.

**Comment by px172** [comment]
Thanks for the update. 

I got the following error (My environment: Windows 7, Firefox 41.0.1. Firebug 2.0.12) 

TypeError: this._d is undefined
...,b,!1);if("viewpointChanged"===a)return void this._d.addOnCameraChanged(b);("mou...
                                                                       
at line 11 when I use https://raw.githubusercontent.com/biasmv/pv/master/bio-pv.min.js

**Comment by biasmv** [comment]
can you try if this works?


```js
viewer1.on('viewerReady', function() {
  viewer1.on('viewpointChanged', function(cam) {
    viewer2.setCenter(cam.center());
    viewer2.setCamera(cam.rotation(), cam.center(), cam.zoom());
  });
});

viewer2.on('viewerReady', function() {
  viewer2.on('viewpointChanged', function(cam) {
    viewer1.setCenter(cam.center());
    viewer1.setCamera(cam.rotation(), cam.center(), cam.zoom());
  });
});

```

**Comment by px172** [comment]
Many thanks for your efforts. It works now.

**Comment by biasmv** [comment]
Great to know!
