### ISSUE TITLE
loadAllModels Uncaught TypeError: structure.assembly is not a function

### ISSUE THREAD

**Issue by spirewebsitedesign** [biasmv/pv#123]
I'm getting the above error when I add the loadAllModels: true option. If I remove the option it loads without any errors. This is happening for all pdbs I tried to load. I'm using version 1.8.1

I believe it's being caused by this, but I'm not sure how to go about fixing it.
    if (opts.loadAllModels) {
      return structures;
    }
    return structures[0];

**Comment by spirewebsitedesign** [comment]
Also I'm passing showRelated: '1' into viewer.cartoon, which is farther up the stacktrace from the error. If I remove that the error changes to:
Uncaught TypeError: obj.chains is not a function

**Comment by biasmv** [comment]
I did a quick test with 1.8.1 and couldn't reproduce the problem. So I'm just taking a guess what the problem could be. If that doesn't turn out to be correct, could you post the code to reproduce the problem? 

My guess is this: When the *loadAllModels* option is enabled the loaded models are returned as an array and you need to handle each of the loaded models separately, e.g. like this:

```js
var models = pv.io.pdb(data, { loadAllModels : true });
models.forEach(function(model, index) { 
  viewer.cartoon('model.'+index, model);
});

```

**Comment by spirewebsitedesign** [comment]
Good guess! That was it, thanks for your help. Yeah I released it was returning an array, I just didn't know what to do with it.

Thanks again.
