### ISSUE TITLE
Citation points to v1.3

### ISSUE THREAD

**Issue by stared** [biasmv/pv#127]
Suggested citation http://dx.doi.org/10.5281/zenodo.12620 points to the version 1.3 (while, right now, we have 1.8.1). Is it the intended behaviour? If so, should I cite it or something different (right now I am writing an academic paper, and we use PV to visualize proteins).

**Comment by biasmv** [comment]
Hi,

sorry for the late reply. No, that's not on purpose. I've updated to reference the latest released version. And yes: I should release a new version soon. v1.8.1 is almost half a year old.

Thanks for pointing this out!

Best,
Marco
