### ISSUE TITLE
Problem with usage of pv.mol.superpose function

### ISSUE THREAD

**Issue by nadziejowo** [biasmv/pv#130]
This issue is supposed to be connected with documentation (http://pv.readthedocs.org/en/latest/superpose.html) but I didn't find any better place to report it.

I want to display two PDBs on one 3D picture but previously I want to superimpose them with the lowest RMSD of matched backbone atoms. I thought that pv.mol.superpose would solve this problem for me. I tried to use this method in that way:

pv.io.fetchPdb(url, function(structure) {
        generatedStrProtein = structure.select('protein')
        bcbComparisonViewer.on('viewerReady', function() {
            bcbComparisonViewer.cartoon('compGenerated', generatedStrProtein,
                        {color : pv.color.uniform('#7cb342')});
        });
(...)}

( the same with nativeStrProtein variable: 
bcbComparisonViewer.cartoon('compNative', nativeStrProtein, {color : pv.color.uniform('lightgrey')}); and then )

var matched = pv.mol.matchResiduesByIndex(nativeStrProtein, generatedStrProtein, 'backbone')
pv.mol.superpose(matched[0], matched[1])
bcbComparisonViewer.requestRedraw();

But the structures aren't superposed on the image. Supposably I use this function in a wrong way but I cannot find a working example in the documentation (or google it elsewhere).

**Comment by biasmv** [comment]
Thanks for the report.

I would assume that this is an issue of ordering your calls. The call to superpose needs to happen before the call to pv.Viewer.cartoon, as the positions already need to be transformed when generating the geometry for rendering. 

You are completely right, the documentation is very light on details. I'll update the documentation when I have time with an example on how to use the functionality. 


As a word of warning: I'm not aware of many people that use the superpose functionality. So it's possible that there are some other rough edges. If you run into any other issues, just let me know and I can try to address them.

**Comment by nadziejowo** [comment]
Thanks, now it works :)

**Comment by biasmv** [comment]
Great to know! I'm closing the ticket. If you run into any issues, just create a new one :).
