### ISSUE TITLE
Adding a custom property

### ISSUE THREAD

**Issue by jergosh** [biasmv/pv#131]
Hi Marco,
I would like to use PV for displaying and colouring structures by custom (continuous) properties. In the documentation I can see that the functionality I want is 
```javascript
pv.color.byResidueProp(prop[, gradient[, range ] ])
```
where  "prop – name of the property to use for coloring. It is assumed that the property is numeric
(floating point or integral). The name can either refer to a custom property, or a built-in
property of atoms or residues."

Which sounds like exactly what I need but what I can't work out is how to add a custom property in the first place?

**Comment by biasmv** [comment]
Hi,

the functionality was not completely implemented until now. I've just pushed a changset to address this. Here is a sample that shows how it can be used:

http://pv.readthedocs.org/en/latest/sample-custom-property.html

I hope that helps.

Best,
Marco

**Comment by jergosh** [comment]
Fantastic, it works perfectly now. Thanks a lot for your help!

Best,
Greg
