### ISSUE TITLE
Pleatedness of beta strands in cartoon mode

### ISSUE THREAD

**Issue by gomoto** [biasmv/pv#135]
Is there a way to control the "pleatedness" of beta strands in cartoon mode?

In PyMOL, for example, you can have smooth beta strands:
![smooth](https://cloud.githubusercontent.com/assets/7393416/11829767/e0f05faa-a353-11e5-9867-eb582ecc2069.png)

or you can have pleated beta strands:
![pleated](https://cloud.githubusercontent.com/assets/7393416/11829776/ed1916aa-a353-11e5-9f3b-b49825bd4929.png)

In PV, beta strands are smooth by default. Is there any way to show them as pleated?

**Comment by biasmv** [comment]
I've just pushed a change that allows you to control the smooting of strands. To disable, you can use:

```js
viewer.cartoon('bla', structure, { smootStrands : false })
```

Best,
Marco

**Comment by gomoto** [comment]
Perfect. Thanks!
