### ISSUE TITLE
Remove sphere from mesh

### ISSUE THREAD

**Issue by darwinFailure** [biasmv/pv#138]
Hi is there's a way to remove a mesh object after drawing it? Did I miss any piece of the manual??

Cheers,
Francesco

**Comment by biasmv** [comment]
Hi Francesco,

I believe you are looking for Viewer.rm, or Viewer.clear:

http://pv.readthedocs.org/en/latest/viewer.html#pv.Viewer.rm
http://pv.readthedocs.org/en/latest/viewer.html#pv.Viewer.clear

Best,
Marco

**Comment by biasmv** [comment]
Hi Francesco,

rereading your question, I now realize that you are asking about removing a particular sphere from a custom mesh object. Sorry the the confusion! To that the answer is, no, that's not possible at the moment. You will have to recreate the whole mesh for now.

To temporarily remove a sphere from the custom mesh, you could also use transparency, though the functionality to change the transparency of a particular sphere is not yet in place. Without having checked in detail, this should be relatively easy to add to PV.

I'd suggest to implement the sphere removal in your code by caching your sphere calculations (center, radius) in an array. Then, just remove the sphere from the array and create a new customMesh object with all the spheres. If you are running into performance issues with this approach, let me know.

Best,
Marco

**Comment by darwinFailure** [comment]
Hi Marco,

Thanks for your answers. Last night I ended up clearing any sphere using pv.Viewer.rm() and noticed the visualization doesn't get refreshed until the orientation change (either by user input or autoZoom()), but it could be me missing something about orientation and camera. Spending the day on it.

Cheers,
Francesco

**Comment by biasmv** [comment]
Hi Francesco,

you can use viewer.requestRedraw() to force a redraw.

Best,
Marco

**Comment by darwinFailure** [comment]
Thanks for your support. Got the job done with viewer.rm and viwer.autoZoom.

Btw, really good piece of sw if compared to competitors ;)

**Comment by biasmv** [comment]
You are welcome!
