### ISSUE TITLE
Cartoon Rendering as Tubes

### ISSUE THREAD

**Issue by spirewebsitedesign** [biasmv/pv#139]
Hi Thank you for this great library. We have been using this for several months now and we recently started using crystal stitched PDBS. Unfortunately these generated PDBs are not rendering properly though they do render correctly in JMOL. I was just wondering if you had any suggestions on what might be the problem?

Thanks for your help!

Cartoon view from jmol:
![cartoon-jmol](https://cloud.githubusercontent.com/assets/1786637/12801699/7f433018-ca93-11e5-8641-96c130fc9fda.PNG)
Cartoon view from pv:
![pv-view](https://cloud.githubusercontent.com/assets/1786637/12801835/9e71582e-ca94-11e5-8cee-47a80eeffa7d.PNG)

**Comment by spirewebsitedesign** [comment]
Ok I think we figured it out. It's happening because we are missing the SHEET meta data. Would there be anyway to remove the dependency on this meta data and just go off the atomic bonds instead?

Thanks

**Comment by biasmv** [comment]
Hi,

glad you like it.

yes you are right, by default PV just uses secondary structure information present in the PDB file. If there is no secondary structure information present, it just renders cartoon as tubes. 

There is code to calculate secondary structure information from the geometry, though it is nowhere as accurate and visually pleasing as the annotations that are in the PDB files. Implementing a more accurate approach for secondary structure annotation will take some time.

Here is how you assign secondary structure information in code, but be warned: the results might not be exactly what you are looking for :)

```js
var structure = pv.io.pdb(data);
pv.mol.assignHelixSheet(structure);
``` 

Best,
Marco

**Comment by spirewebsitedesign** [comment]
Hi Marco,

This helps a lot! Thank you very much.

Arthur
