### ISSUE TITLE
Exposing atom serial number for custom coloring operation

### ISSUE THREAD

**Issue by andrewguy** [biasmv/pv#141]
Hi Marco, 

Firstly, just wanted to say thanks for developing this tool - it's been incredibly useful. 

I'm currently using PV Viewer to display the results of various metrics applied to a protein structure (ie. levels of polymorphism, solvent accessible surface area etc). This involves a custom coloring operation applied to each atom:

```
return new pv.color.ColorOp(function(atom, out, index) {
    var score = colorData[atom.index()];
    if (score == 'None' || score == null) {
      out[index+0] = 1;
      out[index+1] = 1;
      out[index+2] = 1;
      out[index+3] = 1;
    } else {
      var colorGrad = getHeatMapColor((score - min)/(max - min));
      out[index+0] = colorGrad[0];
      out[index+1] = colorGrad[1];
      out[index+2] = colorGrad[2];
      out[index+3] = 1;
      // index + 0, index + 1 etc. are the positions in the output array
      // at which the red (+0), green (+1), blue (+2) and  alpha (+3)
      // components are to be written.
    }
```

It seems that the atom index used by PV does not align properly to the atom serial number in the PDB file, which I have been using to reference the output score for each atom/residue. In particular, atoms with alternate locations are skipped in the PV indexing scheme (ie. `alt_loc !== ' ' && alt_loc !== 'A'`), but retained in the PDB file serial number indexing scheme.

Is there a quick way of exposing the atom serial number within the custom ColorOp, or would this require changes to the existing code?

Cheers,
Andrew

**Comment by biasmv** [comment]
Hi Andrew,

I've just pushed some changes to parse the serial number from PDB files. The property is stored in every atom and is available as atom.serial(). 

I hope that helps

Best,
Marco

**Comment by andrewguy** [comment]
Hi Marco,

That is perfect - very much appreciated!

Cheers,

Andrew

**Comment by andrewguy** [comment]
Hi Marco,

Sorry to reopen this issue/feature request again.  I've gone and implemented a call to `atom.serial()` within a custom ColorOp. It works perfectly when calling:

```
function loadPDB() {
  pv.io.fetchPdb('1zro.pdb', function(structure) {
      structView = structure;

      //Get colour info
      getColorInfo("color_data", function(results) {

        viewer.lines('protein', structView, { color : colorByFile(results) });

        viewer.centerOn(structView);
      });


  });
}
```

where `getColorInfo` is an ajax request with a callback.

However, when altering the 3rd line to define a selection (MolView object I think?):

```
...
structView = structure.select('protein');
...
```
the custom ColorOp fails to color anything. Calling `atom.index()` instead of `atom.serial()` within the ColorOp restores the color. 

Strangely, there doesn't seem to be any issue when using the `cartoon()` geometry, just with most (or all) of the other geometries.

Is this an issue with a MolView not exposing the atom.serial() property properly? Had a poke through the code, but can't see anything obvious.

Cheers,

Andrew

**Comment by biasmv** [comment]
Hi Andrew,

true, I've not tested the MolView version. There is a bug in the getter. Will fix either tonight or tomorrow.

**Comment by biasmv** [comment]
It's fixed now.

**Comment by andrewguy** [comment]
Hi Marco,

That works beautifully now. Cheers!

Andrew
