### ISSUE TITLE
WebGL Error on mobile, v1.9.0dev

### ISSUE THREAD

**Issue by ajfarkas** [biasmv/pv#146]
Current version is 1.9.0: my 1st gen Moto X (~2014) I get the 'WebGL not supported' message

*but*

I can run the [demo](http://biasmv.github.io/pv/demo.html), which is v1.7.0, just fine on the same device.

Any idea what difference may be causing this, and if it can be overcome?

**Comment by ajfarkas** [comment]
I should probably give more detail:
I'm using this small [demo](http://dynamoidapps.com/Wiley/pvsample) I made on v1.9.0. (Please forgive the hackiness).

I'm using chrome (v 49.0.2623.91) on Android 5.1.0, and chrome dev tools (v 46.0.2490.86).
I'm asking for help on this because inspecting the page with v1.9.0 on it causes Chrome debug tools to crash, and I have to restart both my computer and phone.

**Comment by ajfarkas** [comment]
Tracked this down to a shader precision issue. See PR #147

**Comment by biasmv** [comment]
I was away from keyboard for the last few days. Thanks for tracking this down!

**Comment by ajfarkas** [comment]
NP, I'm also working on touch support for the `click` function. Should I
open that as an issue?

**Comment by biasmv** [comment]
Ah, great! Feel free to open a ticket for that.
