### ISSUE TITLE
unable to set selectionColor alpha

### ISSUE THREAD

**Issue by ajfarkas** [biasmv/pv#150]
when I set `Viewer.options.selectionColor` to `[1, 0, 0, 0.2]`, the alpha is overridden.
I'd like to be able to apply custom transparency to this option.

I'll work on this today.

**Comment by ajfarkas** [comment]
While I'm still getting familiar with WebGL, could someone correct some of my assumptions?

I see that `shaderProgram.selectionColor` is defined as a [uniform location](https://github.com/biasmv/pv/blob/master/src/gfx/canvas.js#L234) for each shader. Is this preventing me from writing a fourth value (alpha)? I also see that the camera `setSelectionColor` function is [limited to 3 values](https://github.com/biasmv/pv/blob/master/src/gfx/cam.js#L334).

I'm not sure how to set the `shaderProgram.selectionColor` to a `vec4UniformLoc`.

Any suggestions?

**Comment by biasmv** [comment]
All shader code currently assumes that the selection color is only RGB. Alpha is hard-coded for each of the shaders to a different value,  But it's certainly possible to make that configurable. I've done a quick experiment with the patch below. You can now set the alpha component of selectionColor as well. It's not completely backwards-compatible as now it's no longer possible to do something like `pv.Viewer(parent, { selectionColor : 'white' })` to get a semi-transparent selection. This will need to be addressed before this can go in. I believe the easiest would be to add an alpha parameter to forceRGB, which is used in case no alpha component is provided as part of the color. I hope that helps as a starting point. 

```
diff --git a/src/gfx/cam.js b/src/gfx/cam.js
index 4ac904c..102f2c8 100644
--- a/src/gfx/cam.js
+++ b/src/gfx/cam.js
@@ -28,6 +28,7 @@ define(
 "use strict";
 
 var vec3 = glMatrix.vec3;
+var vec4 = glMatrix.vec4;
 var mat4 = glMatrix.mat4;
 
 function floatArraysAreEqual(lhs, rhs) {
@@ -62,7 +63,7 @@ function Cam(gl) {
   this._outlineColor = vec3.fromValues(0.1, 0.1, 0.1);
   this._outlineWidth = 1.0;
   this._outlineEnabled = true;
-  this._selectionColor = vec3.fromValues(0.1, 1.0, 0.1);
+  this._selectionColor = vec4.fromValues(0.1, 1.0, 0.1, 0.7);
   this._center = vec3.create();
   this._zoom = 50;
   this._screenDoorTransparency = false;
@@ -332,7 +333,11 @@ Cam.prototype = {
     this._outlineColor = vec3.clone(color);
   },
   setSelectionColor : function(color) {
-    this._selectionColor = vec3.clone(color);
+    if (color.length === 3) {
+      this._selectionColor = vec4.fromValues(color[0], color[1], color[2], 0.7);
+    } else {
+      this._selectionColor = vec4.clone(color);
+    }
   },
 
   // sets all OpenGL parameters to make this camera active.
@@ -382,7 +387,7 @@ Cam.prototype = {
     gl.uniform1f(shader.fogNear, this._fogNear + nearOffset);
     gl.uniform3fv(shader.fogColor, this._fogColor);
     gl.uniform3fv(shader.outlineColor, this._outlineColor);
-    gl.uniform3fv(shader.selectionColor, this._selectionColor);
+    gl.uniform4fv(shader.selectionColor, this._selectionColor);
     gl.uniform2fv(shader.relativePixelSize, this._relativePixelSize);
     gl.uniform1f(shader.outlineWidth, this._outlineWidth);
     gl.uniform1i(shader.screenDoorTransparency, this._screenDoorTransparency);
diff --git a/src/gfx/shaders.js b/src/gfx/shaders.js
index 497f24d..0d2752b 100644
--- a/src/gfx/shaders.js
+++ b/src/gfx/shaders.js
@@ -51,10 +51,10 @@ int intMod(int x, int y) { \n\
   return x-y*z;\n\
 }\n\
 \n\
-uniform vec3 selectionColor;\n\
+uniform vec4 selectionColor;\n\
 \n\
 vec3 handleSelect(vec3 inColor, float vertSelect) { \n\
-  return mix(inColor, selectionColor, step(0.5, vertSelect) * 0.7); \n\
+  return mix(inColor, selectionColor.rgb, step(0.5, vertSelect) * selectionColor.a); \n\
 } \n\
 \n\
 uniform bool fog;\n\
@@ -90,10 +90,10 @@ uniform float fogNear;\n\
 uniform float fogFar;\n\
 uniform vec3 fogColor;\n\
 uniform bool fog;\n\
-uniform vec3 selectionColor;\n\
+uniform vec4 selectionColor;\n\
 \n\
 void main(void) {\n\
-  gl_FragColor = mix(vec4(0.0, 0.0, 0.0, 0.0), vec4(selectionColor, 1.0), \n\
+  gl_FragColor = mix(vec4(0.0, 0.0, 0.0, 0.0), vec4(selectionColor.rgb, 1.0), \n\
                      vertSelect);\n\
   gl_FragColor.a = step(0.5, vertSelect);\n\
   if (gl_FragColor.a == 0.0) { discard; }\n\
@@ -246,7 +246,7 @@ varying float vertSelect;\n\
 uniform vec3 outlineColor;\n\
 \n\
 void main() {\n\
-  gl_FragColor = vec4(mix(outlineColor, selectionColor, \n\
+  gl_FragColor = vec4(mix(outlineColor, selectionColor.rgb, \n\
                           step(0.5, vertSelect)), \n\
                       vertAlpha);\n\
   gl_FragColor.rgb = handleFog(gl_FragColor.rgb);\n\
```

**Comment by ajfarkas** [comment]
Thanks. I'm glad to see I wasn't off in my understanding of `cam.js`, but `shaders.js` is still unfamiliar to me. This is a huge help.

**Comment by ajfarkas** [comment]
as far as using color strings and alpha, are you talking about allowing people to define the color and alpha of selections in separate config variables?, ie `pv.Viewer(parent, { selectionColor : 'white', selectionAlpha : 0.5 })`?

**Comment by biasmv** [comment]
Yep, shaders.js is relatively complex. There is a lot of implicit knowledge encoded in the shaders that should be documented one way or another.

Having separate variables for RGB and alpha is certainly also an option. I haven't really thought about that one. I was more thinking to have an implicit alpha of 0.7 if it is not provided as selectionColor. When using a color name, 3-tuple, `#rgb`, `#rrggbb` alpha would be implicitly set to 0.7. However, when providing the color as a 4-tuple, `#rgba` or `#rrggbbaa`, the provided alpha would used. This behavior is a little more subtle, so your suggestion is probably the better one as it's clearer what is going to happen.  The important thing for me is that the change is backward compatible. So whichever solution you are going to implement is fine :).
