### ISSUE TITLE
REMARK 465

### ISSUE THREAD

**Issue by simonbrent** [biasmv/pv#152]
Hi,

We would like to be able to label/render specific residues in a PDB structure based on chain ID:Residue Number combinations. Currently we are basing this on the internal numbering generated by PV but this does not appear to take into account missing residues in the structure (as detailed in REMARK 465) resulting in wrong placement of labels and rendering. Is it possible to render specific atoms on specific residues using chain identifier and PDB residue numbers?

Thanks.

**Comment by biasmv** [comment]
PDB residue numbers and insertion codes are stored for each residue as `num` and `insCode`. To lookup a residue with a given residue number, you can use `residueByRnum` on the chain, e.g. `structure.chain('A').residueByRnum(5)` to get the residue with residue number 5. `residueByRnum` does not support insertion codes yet, so if you depend on insertion codes you will need to manually loop over the chain. We have recently added support for the sequential atom ids stored in the PDB files. They are stored for each atom as the `serial` property. You will need to update to master for this to work as this change is not yet included in any release.

I hope that helps

**Comment by simonbrent** [comment]
Ok, thanks

**Comment by massinovitch** [comment]
Hello , you say : ' insertion codes you will need to manually loop over the chain'. How can I do this to color residues for chain by custom color code.

Thanks,

**Comment by biasmv** [comment]
To implement a custom color operation, you can follow [this guide](http://pv.readthedocs.io/en/v1.8.1/coloring.html#adding-a-new-color-operation). Inside the callback, instead of using atom properties, you can get back to the parent residue the atom belongs to by calling `atom.residue()`. Then it's up to you to map the the residue properties to the color. Does this answer your question? If not, could you elaborate what you are trying to achieve?

**Comment by massinovitch** [comment]
Hello,

Thank you for your response.

I succeeded to implement residues number coloration with this code :

go.colorBy(color.uniform(codeColorResidue), go.select({chain:id, rnumRange:
[numRes1, numResidue2]}));

Cdt,

Massinissa SEKHI
06.83.13.90.62
01.76.84.42.79

2017-02-23 5:51 GMT+01:00 Marco Biasini <notifications@github.com>:

**Comment by massinovitch** [comment]
Hello,

I want to color residues of one chain.
I do it with this function :
function colorstructuraletterpv() {
 viewer.forEach(function(go) {
for (numChain in listColorResidues) {
var listColorResiduesForChain = listColorResidues[numChain];// i get
listColorResidues
by file.
for (numResidue in listColorResiduesForChain) {
codeColorResidue = listColorResiduesForChain[numResidue];
var numResidueInt = parseInt(numResidue);
go.colorBy(color.uniform(codeColorResidue), go.select({chain:numChain,
rnumRange: [numResidueInt, numResidueInt]}));
}
}
 });
 viewer.requestRedraw();
}

but it take time considerable (>500 ms). is there another faster way to
color just one chain in the structure by residues.

thank you.

Massinissa SEKHI
06.83.13.90.62
01.76.84.42.79

2017-02-24 9:49 GMT+01:00 Massinissa SEKHI <sekhi.massinissa@gmail.com>:
