### ISSUE TITLE
Viewer.fitTo multiple MolView objects

### ISSUE THREAD

**Issue by gomoto** [biasmv/pv#154]
What is the best way to center a viewer on multiple MolViews across multiple structures? 

Is it possible to combine MolViews into one object on which I can call Viewer.fitTo?
Would you consider an extended method signature for Viewer.fitTo that centers the viewer on the centroid of an arbitrary number of objects?

**Comment by biasmv** [comment]
Looking at the code, this should already be possible. Have you tried to pass an array of mol views to fitTo?

**Comment by gomoto** [comment]
Works perfectly. Sorry, I assumed only one MolView could be fitTo based on the docs. Thanks for explaining!

**Comment by biasmv** [comment]
Hmm, in that case the docs are not accurate enough. I'll add the list-based fitTo signature to the documentation
