### ISSUE TITLE
Colour structure by custom residue id mapping (e.g. temperature factors) 

### ISSUE THREAD

**Issue by tomnewport** [biasmv/pv#158]
I have a few attributes assigned on a per-residue basis which I'd like to be able to use to colour the cartoon representation. This could be done by colouring by temperature factors, although that would mean loading a new structure every time a new attribute was selected. 

Any thoughts?

**Comment by biasmv** [comment]
Hi Tom,

you can add custom properties to atoms and residues through `setProp`. You can then use the property in a color.byAtomProp, or color.byResidueProp call. Something like this should work (untested):

```js
var index = 0;
structure.eachResidue(function(r) {
  r.setProp('funky', index++ % 50);
});

var go = viewer.cartoon('v', structure, { color : pv.color.byResidueProp('funky') });
```

Let me know if that works for you.

**Comment by tomnewport** [comment]
This looks great! I'll have a go and let you know how I get on.

**Comment by tomnewport** [comment]
(sorry, finally implementing this!)

I'm trying the following code:

```javascript
    var protein = structure.select('protein');
    protein.eachResidue(function(r) {
          console.log(r)
          r.setProp('funky', index++ % 50);
      });
     viewer.cartoon('protein', protein, {color:pv.color.byResidueProp('funky')});
```

This produces the following log:

```javascript
Object { _c5: Object, _j: Array[3] } simDirective.js:60:13
Object { _er: Object, _r: Array[4], _v: Object } simDirective.js:62:15
TypeError: r.setProp is not a function
```

Any ideas?

**Comment by tomnewport** [comment]
The residue does have a prop method, although I'm not sure how to call it:

```javascript
>>> r.prop
function E</c.prototype.prop()
>>> r.prop("funky")
TypeError: this[a] is not a function
```

**Comment by biasmv** [comment]
Hi Tom,

apologies for the late reply. Probably the reply comes too late to be relevant :(. 

You will have to use the latest version in master for this to work. There have been a few fixes in this area of the code. 

Best,
Marco

**Comment by tomnewport** [comment]
Is that the same as the latest bower release?

(No worries! You underestimate how slowly I work - I was just about to implement this.)

**Comment by biasmv** [comment]
The feature is only available in master. You should be able to use the version from master by calling
```
bower install bio-pv#master
```

Best,
Marco

**Comment by tomnewport** [comment]
Amazing - is there any way to change the colour scale or define a custom colour scale?

**Comment by RasmusFonseca** [comment]
1) http://pv.readthedocs.io/en/v1.8.1/coloring.html#custom-color-palettes

2) Check out https://github.com/biasmv/pv/blob/master/src/mol/residue.js. This should work, though I didn't test it:

```javascript
protein.eachResidue(function(r){
  console.log(r.index()+"_"+r.name());
});
```

**Comment by tomnewport** [comment]
That worked perfectly, thanks @RasmusFonseca and @biasmv.
