### ISSUE TITLE
Transform model position

### ISSUE THREAD

**Issue by ajfarkas** [biasmv/pv#161]
I'd like to place multiple models in a single scene without superposing them:  
is there a method for model position translations? Something like `Cam.setCenter()`?

**Comment by RasmusFonseca** [comment]
https://pv.readthedocs.io/en/v1.8.1/viewer.html#pv-viewer-camera :
```pv.Viewer.setCenter(center[, ms])```

**Comment by ajfarkas** [comment]
Ah, I mean something like `Cam.setCenter()`, but for positioning models.  
My models are currently overlapping, and I'd like to separate them.

**Comment by RasmusFonseca** [comment]
This works for me:
```javascript
var parent = document.getElementById('viewer');
var viewer = pv.Viewer(parent, { width : 600, height : 600, antialias : true });
viewer.on('viewerReady', function() {
  pv.io.fetchPdb('3k0n.pdb', function(structure) {
    viewer.cartoon('prot1', structure);
  });
  pv.io.fetchPdb('3k0n.pdb', function(structure) {
    var delta = [3,0,0];
    structure.eachAtom(function(atom){
      var pos = atom.pos();
      var newPos = [pos[0]+delta[0], pos[1]+delta[1], pos[2]+delta[2]];
      atom.setPos( newPos );
    });

    viewer.cartoon('prot2', structure);
  });
});
```
You could wrap that in a `setCenter` function

**Comment by ajfarkas** [comment]
Wow, I couldn't see the forest for the trees. Thanks.
