### ISSUE TITLE
Viewer height

### ISSUE THREAD

**Issue by polaton** [biasmv/pv#163]
Hi Marco,

I tried the new minified JS and I had a annoying bug.

My viewer declaration is the following:

var options = {
  width: 'auto',
  height: 450,
  antialias: true,
  quality : 'medium',
  fog : 'false'
};
var viewer = pv.Viewer(document.getElementById('viewer'), options);

And the generated HTML is the following:
<canvas width="3808" height="900" style="transform: translate(-952px, -225px) scale(0.5, 0.5);"></canvas>

The viewer is only 450 height, but the canvas is 900, leaving a white empty useless space.

I joined an image for you to get a better grasp on the problem I encounter.

Have a nice day,
Antoine

![pvbug](https://cloud.githubusercontent.com/assets/11832034/16922395/9d9dcea6-4d15-11e6-9cce-83f080b5c3e4.png)

**Comment by biasmv** [comment]
I'm assuming this is due to "manual" antialiasing on your device. Does it help to disable manual antialiasing by passing `forceManualAntialiasing : false` when you construct the viewer?

**Comment by polaton** [comment]
Hi Marco,

Thanks for your answer. It's working fine now!

Have a nice day.

2016-07-18 22:03 GMT+02:00 Marco Biasini <notifications@github.com>:
