### ISSUE TITLE
Get Camera/ Current Rotation Matrix From Viewer

### ISSUE THREAD

**Issue by spirewebsitedesign** [biasmv/pv#164]
In order to allow me to programmatically move the camera around to focus on different features of residues I need to get the current rotation from the viewer object. Then I can multiply that with a rotation matrix and set the result using the viewer.setRotation function.

Previously I was getting it like this:
viewer._cam.rotation()

This no longer works though as the new minified version has renamed all the private variables. :-/

Can I add a getCamera (or getRotation) method to the viewer object and submit a PR?  Or do you have any other suggestions?

Thanks

**Comment by biasmv** [comment]
Took me a while to get back to this: The viewer has a method called rotation() to get the current rotation matrix as a mat4. The method only exists in master, but not in the latest release. This reminds me: I should really get to releasing 1.9.0.  Does that work for what you need?

**Comment by spirewebsitedesign** [comment]
Yes that works. Thank you!
