### ISSUE TITLE
setSelectionColor

### ISSUE THREAD

**Issue by gomoto** [biasmv/pv#166]
Is there a way to set selection color after the viewer initializes? It seems like I could call Cam. setSelectionColor, but the camera is private to the viewer. Any suggestions?

**Comment by biasmv** [comment]
Does `viewer.options('selectionColor', newColor)` work for you?

**Comment by gomoto** [comment]
Ahh cool thanks.

**Comment by gomoto** [comment]
How can I get the selection color to change immediately? In [this plunker] (http://plnkr.co/sOGXMtoXOeVwue4A9hvy), I call viewer.options() in response to a click, but the selection color doesn't change. Then I call requestRedraw(), but still no change. Once I move the viewer, the selection color changes.

**Comment by biasmv** [comment]
That's most likely a bug. I'll look into it tonight.

**Comment by biasmv** [comment]
It's working now.
