### ISSUE TITLE
Fixed label in front of camera

### ISSUE THREAD

**Issue by giagitom** [biasmv/pv#168]
Hi, i need to insert a label inside my viewer and keep it fixed in the center of the viewer while moving, rotaitng etc.. (i can't use a div block like in the example shown in the documentation, i need something embedded in the canvas element of the viewer). Is there an easy way to do it? Like drawing 2D transparent texture unwrapped from the camera object..

Thanx! Beautifull app!

**Comment by biasmv** [comment]
There is no built-in solution to do that. It should be possible to update the position of the label every time the camera rotates, shifts etc to keep the label at the same position. There is an event that gets invoked every time the viewpoint changes you can use:
```js
viewer.on('viewpointChanged', function(camera) {
    // update label position here by removing and readding the label
});
```

Best,
Marco

**Comment by giagitom** [comment]
I was trying to use this approach, but I didn't know how to calculate the new position for the label.. mybe I'm wrong but i think it involves some matrix multiplication and inversion to transform the old label position in the new position, but I don't know how to obtain the transformation matrix.. 

I also noticed that the text shown in the viewer is cropped more and more increasing the label size ( > 35) (I tried on chrome and firefox on viewer version 1.9.0).

**Comment by biasmv** [comment]
The easiest is to take the center of rotation and then shift the label along the negative viewing direction of the camera. This code should do what you want:

```js
viewer.addListener('viewpointChanged', function(camera) {
    viewer.rm('label');
    var opts = {
        fontSize : 16, fontColor: '#f00'
    };
    var v = pv.vec3.create();
    pv.vec3.scaleAndAdd(v, camera.center(), camera.mainAxes()[2], 10);
    viewer.label('label', 'Your ad here', v, opts);
});
```

You will have to play around with the amount of shifting to place the label in front of what you want to display. You might get good results with using the value of `camera.zoom()` minus a fixed value.

Thanks for the report regarding the rendering issues with larger label sizes. Are you referring to larger font sizes or labels with more text in them? Could you create a separate ticket for this issue? I'll look then into it.

**Comment by giagitom** [comment]
Great! It works perfectly. If I would like to display the label laterally instead? What should I change to keep it fixed? 

Thank you!

**Comment by biasmv** [comment]
The other two axes (x and y) are contained in `camera.mainAxes()[0]` and `camera.mainAxes()[1]`.

**Comment by giagitom** [comment]
Yes, i tried changing `camera.mainAxes()[2]` with `camera.mainAxes()[0]` and a fixed translation on right occours, but how to combine translation between z and x for example? I tried in this fashion without luck:  
```js
var x =  pv.vec3.create();
pv.vec3.scaleAndAdd(x, camera.center(), camera.mainAxes()[0], 100);
var z = pv.vec3.create();
pv.vec3.scaleAndAdd(z, camera.center(), camera.mainAxes()[2], camera.zoom()-10);
var pos = pv.vec3.create();
pv.vec3.scaleAndAdd(pos, z, x, 1);
label(pos);
```

**Comment by biasmv** [comment]
This works for me:

```js
viewer.addListener('viewpointChanged', function(camera) {
    viewer.rm('label');
    var opts = {
        fontSize : 16, fontColor: '#f00'
    };
    var v = pv.vec3.create();
    var axes = camera.mainAxes();
    pv.vec3.scaleAndAdd(v, camera.center(), axes[2], 10);
    pv.vec3.scaleAndAdd(v, v, axes[0], 10);
    viewer.label('label', 'Your ad here', v, opts);
});
```

The vector operations are implemented with gl-matrix.js, which is a little awkward to use, but is very efficient if have to perform many vector operations. The signature is function `scaleAndAdd(out, a, b, s)`, where `out = a + b * s`, `a` and `b` are vectors, `s` is a scalar.

**Comment by giagitom** [comment]
Thank you! It works great!

Yes I looked at gl-matrix.js before, the main problem for me was the camera concept and the math behind it i think..

**Comment by biasmv** [comment]
Great, glad I could help.

**Comment by giagitom** [comment]
Hi Marco, I encountered a problem updating the label in front of camera in firefox.. (in google chrome it works fine)

The viewer is greatly slowed down and 2 errors are thrown in console at every refresh of the label:

Error: WebGL: texImage2D: Incurred CPU pixel conversion, which is very slow.

Error: WebGL: texImage2D: Chosen format/type incurred an expensive reformat: 0x1908/0x1401

both errors are pointing hear:
gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA,
                  gl.UNSIGNED_BYTE, srcCanvas);

Any idea on how to solve this problem? 

Thank you!
