### ISSUE TITLE
Increasing label font size issue

### ISSUE THREAD

**Issue by giagitom** [biasmv/pv#170]
I also noticed that the text shown in the viewer is cropped more and more increasing the label size ( > 35) (I tried on chrome and firefox on viewer version 1.9.0).

Hear an Example label rendered with fontsize 45
![example](https://cloud.githubusercontent.com/assets/20627977/21072785/27ff4a64-bece-11e6-895b-174222700157.png)

**Comment by biasmv** [comment]
I've just pushed a fix to this issue.

**Comment by giagitom** [comment]
Thank you!
