### ISSUE TITLE
error when used as amd module

### ISSUE THREAD

**Issue by sgratzl** [biasmv/pv#75]
I tried using this library as an AMD module. However, I got an error that vec3 is not defined. 

`pv-v1.3.rel.js:3235 Uncaught ReferenceError: vec3 is not defined`

relevant code:
```js
var geom = (function() {
  "use strict";
  // calculates the signed angle of vectors a and b with respect to
  // the reference normal c. 
var signedAngle = (function() {
    var tmp = vec3.create(); <-- vec3 not defined
```

**Comment by biasmv** [comment]
Sorry about that. AMD currently doesn't have the attention it deserves. I'm planning to work on that in the next few days. For now, I'd suggest to build directly from the github repo and use that. I'll let you know once I've finished modularizing everything.

Best,
Marco

**Comment by biasmv** [comment]
I've just pushed a few patches to the require-js branch to use AMD loading for the PV code-base. This should also fix the issue you were seeing. 

I'll have to update the documentation and run some additional tests before merging this into master. 

Best,
Marco

**Comment by sgratzl** [comment]
thanks, I will try it out

**Comment by biasmv** [comment]
I'm going to close this. Feel free to reopen, file a new bug in case you find any issues.

Best,
Marco

**Comment by sgratzl** [comment]
Hi, sorry for the late response. I tested 1.4.0 and it works like a charm - thx!
