### ISSUE TITLE
accessing residues by pdb residue id

### ISSUE THREAD

**Issue by andreassteffen** [biasmv/pv#78]
Hi,
according to the documentation i can access protein residues only based on a zero based index. is it possible to access a residue by the id it has in the PDB file, e.g. by id 56 as in the snipplet below?
Thanks, Andreas
ATOM    394  N   SER A  56      12.152 -53.306  -4.665  1.00 45.76           N  
ATOM    395  CA  SER A  56      12.199 -53.439  -3.207  1.00 45.89           C  
ATOM    396  C   SER A  56      10.808 -53.814  -2.716  1.00 46.50           C  
ATOM    397  O   SER A  56       9.872 -53.877  -3.513  1.00 47.46           O  
ATOM    398  CB  SER A  56      12.603 -52.111  -2.568  1.00 45.17           C  
ATOM    399  OG  SER A  56      11.592 -51.138  -2.779  1.00 42.23           O

**Comment by biasmv** [comment]
Yes, you can use the ```Residue.num()``` and ```Residue.insCode()``` properties.  Either you manually loop through the residues and select the ones that match the residue number you want, or you use ```Chain. residuesInRnumRange(start,end)```. It's also possible to use ```Mol.select({rnum : 1}})```, ```Mol.select({rnums:[1,23]})```, or ```Mol.select({rnumRange : [1, 20]})```. 

**Example: Coloring residues with numbers 20...30 in red**

```javascript
var structure = io.pdb(...);
var go = viewer.cartoon('structure', structure);
go.colorBy(color.uniform('red'), structure.select({rnumRange: [20, 30]}));
```

I'll add descriptions for these functions to the docs.


Best,
Marco

**Comment by andreassteffen** [comment]
thanks, that's great!
