### ISSUE TITLE
SDF file

### ISSUE THREAD

**Issue by andreassteffen** [biasmv/pv#79]
Hi,
are you considering adding support for [SD files](http://en.wikipedia.org/wiki/Chemical_table_file#SDF)?
That would enable being able to load 3D structures of small molecules (e.g. docking poses) into the viewer.
Cheers, Andreas

**Comment by biasmv** [comment]
Hi,

I've pushed a very simple parser for the SDfile format. It supports  reading of atom data and connectivity table. In case multiple molecules are present, they are imported into the same structure, but as different chains.

The parser does not read any other information at the moment, for example custom properties, bond order, charge etc, so if you need that, support would have to be added.

**Comment by andreassteffen** [comment]
many thanks, that's great! bond order would be good, but it's already a great start!
