### ISSUE TITLE
Spin command

### ISSUE THREAD

**Issue by andreasprlic** [biasmv/pv#80]
I was looking at using PV to run animations. Something like the Jmol "spin" command would be great. I.e. a continuous rotation around one of the axes. Would that be hard to add?

Thanks, and congrats on the new release btw!

Andreas

**Comment by biasmv** [comment]
I've added support for spin animations:

http://pv.readthedocs.org/en/latest/viewer.html#pv.Viewer.spin

I've made a few modifications to the animation system to properly process user input while spin/rockAndRoll are running. Before, it was no longer possible to rotate the camera with the mouse.

You can also mix the spinning with rock and roll:

```javascript
viewer.spin(Math.PI/8, [1, 0, 0]);
viewer.rockAndRoll(true);
```

Best,
Marco

**Comment by andreasprlic** [comment]
This is great, thanks! Rebuilt my checkout and works like a charm.

Thanks,

Andreas
