### ISSUE TITLE
problem at init

### ISSUE THREAD

**Issue by andreasprlic** [biasmv/pv#84]
Hi,

just update to latest checkout. There seems to be an issue during startup. I am getting a 

"ReferenceError: canvas is not defined" from this line in viewer.js:
isWebGLSupported: canvas.isWebGLSupported

A

**Comment by biasmv** [comment]
Hi,

it's fixed now. This was caused by a bug in AMDclean. 

Best,
Marco

**Comment by andreasprlic** [comment]
Thanks for the quick fix. I confirm it works again, also #82 .
