### ISSUE TITLE
viewer.quality does not cause quality to update or change

### ISSUE THREAD

**Issue by tomnewport** [biasmv/pv#85]
I'm trying to change the viewer quality after initialisation using 
    
        viewer.quality("low")
        viewer.quality("high")

But this does not seem to change how the model is displayed. Am I doing something wrong or is this a bug?

**Comment by biasmv** [comment]
this option only affects objects that are created *after* changing the quality. It won't modify any existing objects:

```javascript
// rendered using  default (medium) quality
viewer.cartoon('medium', myStructure);
viewer.quality('low');
// rendered using low quality
viewer.cartoon('low', myStructure);
```
I've clarified the docs to make it clear that only newly created geometry is affected by the property change.

**Comment by tomnewport** [comment]
Thanks! (and thanks for providing such a great tool)
