### ISSUE TITLE
Set FOV or use orthographic projection

### ISSUE THREAD

**Issue by tomnewport** [biasmv/pv#86]
I would like to be able to either set field of view manually or toggle orthographic projection. Is this currently possible?

**Comment by biasmv** [comment]
Hey,

I've added support for setting the field of view manually. You can either set it when constructing the viewer, or via "options" later on:

```javascript
var viewer = pv.Viewer(..., { fov: 60 });
viewer.options('fov', 45);
```

It's possible that some parts of the viewer behave strangely when changing the field of view. Let me know if you encounter any strange effects.

**Comment by tomnewport** [comment]
Thank you - I had been using 

        pvViewer._cam._fovY = 0.2

I'll update my code now!
