### ISSUE TITLE
colorOne is undefined

### ISSUE THREAD

**Issue by rlowe55** [biasmv/pv#87]
Hi,
for some molecules - example 2LYZ - I get this error - 'colorOne is undefined' - when switching to chain coloring
my code is:
    viewer.forEach(function(go) {
	go.colorBy(color.byChain(), proteinStructure);
    });
where proteinStructure is defined as:
    proteinStructure 	= structure.select("protein");

the error is not critical - but I am seeing it the logs
thanks,

**Comment by biasmv** [comment]
Hi Rob,

thanks for the report. Would it be possible to also share the code you use generate "go"? I've tried all rendering modes and couldn't get the "colorOne is undefined" reproduced.

Best,
Marco
