### ISSUE TITLE
1M8Q not recognizing alpha helices in secondary structure coloring

### ISSUE THREAD

**Issue by rlowe55** [biasmv/pv#88]
Hi,
when I load 1M8Q it does not recognize the alpha helices - only the beta sheets are colored differently when selecting secondary structure coloring
thanks,
rob

**Comment by rlowe55** [comment]
Hi Marco,
actually I just discussed this with one of the annotators here at RCSB - it seems that the pdb file itself does not contain any alpha-helix records (even tho they are present in the structure) - so this is clearly not a pv issue. I am closing this ticket.
thanks

**Comment by biasmv** [comment]
OK, good to know! 

Best,
Marco
