### ISSUE TITLE
Point Cloud Representation

### ISSUE THREAD

**Issue by tomnewport** [biasmv/pv#89]
I have around 47,000 3D points saved as atoms in a pdb file which I'd like to view as a point cloud. I was looking at the custom mesh api for that, but it's rather too many points to represented as spheres. Would this be possible in PV?

**Comment by biasmv** [comment]
I've just added viewer.points() to render a structure as a point-cloud.  This should cover your use-case.

```js
io.fetchPdb('...', function(structure) {
   viewer.points('points', structure);
   viewer.autoZoom();
});
```
Best,
Marco
