### ISSUE TITLE
transparency not working

### ISSUE THREAD

**Issue by kozmad** [biasmv/pv#93]
Dear Marco, 

I was trying to make a surface transparent, but did not succeed.
![kepernyokep 2015-04-28 11 52 40](https://cloud.githubusercontent.com/assets/8612853/7367056/1a15d318-ed9d-11e4-930b-81752e04d2e5.png)

Than I've added at LINE 317 the following command and it's got worked: 
```
this._gl.blendFunc(this._gl.SRC_ALPHA, this._gl.ONE_MINUS_SRC_ALPHA);
```

May I forgot something to enable from my script? Or it was a real issue. If yes, I hope my report and solution helps. But in Chrome, there is still an issue with transparency.

FIREFOX:
![kepernyokep 2015-04-28 11 50 18](https://cloud.githubusercontent.com/assets/8612853/7367012/cb8b2694-ed9c-11e4-8a03-5a30ad4b69ff.png)

CHROME:
![kepernyokep 2015-04-28 11 49 30](https://cloud.githubusercontent.com/assets/8612853/7367017/d1dabeba-ed9c-11e4-88f7-d58e2e3f2cb5.png)

Could you advice me an easier solution for setting the opacity level of a surface?
```
membrane = viewer.surface('membrane', mem);
for( var i=9; i<membrane._indexedVAs[0]._vertData.length; i+=membrane._indexedVAs[0]._FLOATS_PER_VERT )
                membrane._indexedVAs[0]._vertData[i] = 0.7;
```

Thank you for your help in advance!

Cheers,
Daniel

**Comment by biasmv** [comment]
Hi Daniel,

from the top of my head, there are a few reason why it doesn't look the way it's supposed to:

- You will have to make sure the protein gets drawn before the membranes. This can be done by adding the protein before the membrane. You can also set the "order" property and sort the objects by order. At the moment, the code for this is only half-baked, so a little manual work from your side is required. After you set the order on the planes you will have to do: ```viewer.all().sort(function(lhs, rhs) { return lhs.order() - rhs.order(); });```
- The ordering of membrane planes is wrong. This doesn't seem to be the case here, but it's certainly and issue for other orientations. You will have to sort the planes every time the orientation of the camera changes to make sure the plane furthest from the camera gets drawn first.

> Could you advice me an easier solution for setting the opacity level of a surface?

Well, you can write a custom shader to set the opacity on the full object at once, but that's probably overkill for these objects. That only really starts to pay off once you have thousands of vertices and you want to animate fade in/fade out.

**Comment by kozmad** [comment]
Dear Marco,

Thank you for your answer, it solves my problem.
The sort() did the trick. :)

Cheers,
Daniel
