### ISSUE TITLE
Allow residue superposition

### ISSUE THREAD

**Issue by blakesweeney** [biasmv/pv#94]
It would be really useful to select two lists of residues and superimpose them using specific atoms. For example, sometimes we want to superimpose by certain phosphates, while other times we want to use different atoms.

**Comment by biasmv** [comment]
Have a look at the newly added superposition functionality here: http://pv.readthedocs.org/en/latest/superpose.html

**Comment by blakesweeney** [comment]
I've looked at the docs and it looks good, but I won't have time to test it out for a week or so. Just so you don't think I've forgotten about this.

**Comment by biasmv** [comment]
I'm going to close the ticket for now. In case it doesn't work for you as intended, feel free to open a new ticket.
