### ISSUE TITLE
fetching pdbs in demo.js stopped working

### ISSUE THREAD

**Issue by julianheinrich** [biasmv/pv#95]
I guess you're missing a '/' in line 211 in demo.js:
```javascript
io.fetchPdb('http://pdb.org/pdb/files' + pdbId + '.pdb', 
              function(s) {
    structure = s;
    cartoon();
    viewer.autoZoom();
  });
```

which results in the following request on the console:
GET http://www.rcsb.org/pdb/files3q01.pdb 
which doesn't exist.

**Comment by biasmv** [comment]
Thanks!
