### ISSUE TITLE
pv.mol.MolView() undefined

### ISSUE THREAD

**Issue by julianheinrich** [biasmv/pv#96]
Hi Marco,

I just stumbled upon another issue:
mol.MolView is not returned in mol/all.js (only in mol/mol.js, which is not defined in pv.js), resulting in pv.mol.MolView() being undefined.

Is that on purpose?

**Comment by biasmv** [comment]
Thanks for the fix. The preferred way to create a new mol view is by calling ```Mol.createEmptyView()```. It does not hurt to have  MolView class exposed.

**Comment by julianheinrich** [comment]
Thanks for clarifying. Must have missed that in the docs.
