### ISSUE TITLE
Opacity not working?

### ISSUE THREAD

**Issue by julianheinrich** [biasmv/pv#99]
I've tried setting the opacity in demo.js just to see how it looks like:
```javascript
function cartoon() {
  viewer.clear();
  var go = viewer.cartoon('structure', structure, {
      color : color.ssSuccession(), showRelated : '1',
  });
  go.setOpacity(0.2);
  var rotation = viewpoint.principalAxes(go);
  viewer.setRotation(rotation)
}
```

resulting in this image after running the demo and selecting the Methyl Transferase:
![screenshot 2015-05-06 17 02 01](https://cloud.githubusercontent.com/assets/7494632/7488744/bbf091da-f411-11e4-8857-e9d120bd371e.png)

Seems like colours are less saturated, but still opaque.
@biasmv  Can you confirm this?

**Comment by biasmv** [comment]
Sorry for the long delay. I was rather busy and didn't have the time to look at it earlier.
